import path from 'path';
import * as vscode from 'vscode';
import * as FileSystem from 'fs';
import { spawn } from 'child_process';

export function activate(context: vscode.ExtensionContext) {
    registerCommands(context);
}

interface UMLMetadata {
    encoded: string;
    url: string;
    generatedOn: string;
    content: string;
}

async function openPlantUMLPreview(uri: vscode.Uri, context: vscode.ExtensionContext) {
    try {
        const content = FileSystem.readFileSync(uri.fsPath, 'utf-8');
        const metadata = extractUMLMetadata(content);
        
        if (metadata) {
            // Create a webview panel to display the UML
            const panel = vscode.window.createWebviewPanel(
                'plantUMLPreview',
                'PlantUML Preview',
                vscode.ViewColumn.Two,
                {
                    enableScripts: true,
                    retainContextWhenHidden: true
                }
            );

            panel.webview.html = getWebviewContent(metadata);
            
            // Handle messages from the webview
            panel.webview.onDidReceiveMessage(
                message => {
                    switch (message.command) {
                        case 'openUrl':
                            vscode.env.openExternal(vscode.Uri.parse(message.url));
                            return;
                        case 'copyUrl':
                            vscode.env.clipboard.writeText(message.url);
                            vscode.window.showInformationMessage('PlantUML URL copied to clipboard!');
                            return;
                        case 'copyEncoded':
                            vscode.env.clipboard.writeText(message.encoded);
                            vscode.window.showInformationMessage('Encoded string copied to clipboard!');
                            return;
                    }
                },
                undefined,
                context.subscriptions
            );
        } else {
            vscode.window.showErrorMessage('Could not extract UML metadata from file. Make sure the file was generated by the UML Generator.');
        }
    } catch (error) {
        vscode.window.showErrorMessage(`Error opening PlantUML preview: ${error}`);
    }
}

function extractUMLMetadata(content: string): UMLMetadata | null {
    const lines = content.split('\n');
    let encoded = '';
    let url = '';
    let generatedOn = '';
    
    // Extract metadata from comments
    for (const line of lines) {
        if (line.startsWith("' Encoded: ")) {
            encoded = line.replace("' Encoded: ", '').trim();
        } else if (line.startsWith("' URL: ")) {
            url = line.replace("' URL: ", '').trim();
        } else if (line.startsWith("' Generated on: ")) {
            generatedOn = line.replace("' Generated on: ", '').trim();
        }
    }
    
    if (encoded && url) {
        return {
            encoded,
            url,
            generatedOn,
            content: content.replace(/^'.*/gm, '').trim() // Remove comment lines for clean content
        };
    }
    
    return null;
}

function getWebviewContent(metadata: UMLMetadata): string {
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>PlantUML Preview</title>
        <style>
            body {
                font-family: var(--vscode-font-family);
                background-color: var(--vscode-editor-background);
                color: var(--vscode-editor-foreground);
                padding: 20px;
                margin: 0;
            }
            .header {
                margin-bottom: 20px;
                padding-bottom: 10px;
                border-bottom: 1px solid var(--vscode-panel-border);
            }
            .metadata {
                background-color: var(--vscode-textBlockQuote-background);
                padding: 15px;
                border-radius: 5px;
                margin-bottom: 20px;
                border-left: 4px solid var(--vscode-textBlockQuote-border);
            }
            .button {
                background-color: var(--vscode-button-background);
                color: var(--vscode-button-foreground);
                border: none;
                padding: 8px 16px;
                margin-right: 10px;
                margin-bottom: 10px;
                border-radius: 3px;
                cursor: pointer;
                font-size: 13px;
            }
            .button:hover {
                background-color: var(--vscode-button-hoverBackground);
            }
            .button.secondary {
                background-color: var(--vscode-button-secondaryBackground);
                color: var(--vscode-button-secondaryForeground);
            }
            .button.secondary:hover {
                background-color: var(--vscode-button-secondaryHoverBackground);
            }
            .image-container {
                text-align: center;
                margin: 20px 0;
                padding: 20px;
                background-color: var(--vscode-textBlockQuote-background);
                border-radius: 5px;
            }
            .image-container img {
                max-width: 100%;
                height: auto;
                border: 1px solid var(--vscode-panel-border);
                border-radius: 3px;
            }
            .code-block {
                background-color: var(--vscode-textCodeBlock-background);
                border: 1px solid var(--vscode-panel-border);
                border-radius: 3px;
                padding: 15px;
                font-family: var(--vscode-editor-font-family);
                font-size: var(--vscode-editor-font-size);
                overflow-x: auto;
                white-space: pre-wrap;
                margin-top: 20px;
            }
            .loading {
                text-align: center;
                color: var(--vscode-descriptionForeground);
                font-style: italic;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>PlantUML Preview</h1>
            <p>Generated on: ${metadata.generatedOn}</p>
        </div>
        
        <div class="metadata">
            <h3>Actions</h3>
            <button class="button" onclick="openUrl()">🌐 Open in Browser</button>
            <button class="button secondary" onclick="copyUrl()">📋 Copy URL</button>
            <button class="button secondary" onclick="copyEncoded()">🔐 Copy Encoded</button>
        </div>
        
        <div class="image-container">
            <div class="loading" id="loading">Loading diagram...</div>
            <img id="diagram" src="${metadata.url.replace('/uml/', '/png/')}" 
                 alt="UML Diagram" style="display:none;"
                 onload="showImage()" 
                 onerror="showError()">
        </div>
        
        <div class="metadata">
            <h3>PlantUML URL</h3>
            <div class="code-block">${metadata.url}</div>
            
            <h3>Encoded String</h3>
            <div class="code-block" style="word-break: break-all;">${metadata.encoded}</div>
        </div>
        
        <details>
            <summary>View PlantUML Source</summary>
            <div class="code-block">${metadata.content}</div>
        </details>

        <script>
            const vscode = acquireVsCodeApi();
            
            function openUrl() {
                vscode.postMessage({
                    command: 'openUrl',
                    url: '${metadata.url}'
                });
            }
            
            function copyUrl() {
                vscode.postMessage({
                    command: 'copyUrl',
                    url: '${metadata.url}'
                });
            }
            
            function copyEncoded() {
                vscode.postMessage({
                    command: 'copyEncoded',
                    encoded: '${metadata.encoded}'
                });
            }
            
            function showImage() {
                document.getElementById('loading').style.display = 'none';
                document.getElementById('diagram').style.display = 'block';
            }
            
            function showError() {
                document.getElementById('loading').innerHTML = '❌ Failed to load diagram. Try opening the URL in browser.';
            }
        </script>
    </body>
    </html>
    `;
}

function registerCommands(context: vscode.ExtensionContext) {
    const generateFromFileCommand = vscode.commands.registerCommand('umlGenerator.generateFromFile', async (uri: vscode.Uri) => {
        try {
            await generateUMLFromFile(uri);
        } catch (error) {
            vscode.window.showErrorMessage(`Error generating UML from file: ${error}`);
        }
    });

    const generateFromFolderCommand = vscode.commands.registerCommand('umlGenerator.generateFromFolder', async(uri: vscode.Uri) => {
        try {
            await generateUMLFromFolder(uri);
        } catch (error) {
            vscode.window.showErrorMessage(`Error generating UML from folder: ${error}`);
        }
    });

    const openSettingsCommand = vscode.commands.registerCommand('umlGenerator.openSettings', () => {
        vscode.commands.executeCommand('workbench.action.openSettings', 'umlGenerator');
    });

    const openPlantUMLPreviewCommand = vscode.commands.registerCommand('umlGenerator.openWebView', async (uri: vscode.Uri) => {
        try {
            await openPlantUMLPreview(uri, context);
        } catch (error) {
            vscode.window.showErrorMessage(`Error opening PlantUML preview: ${error}`);
        }
    });

    context.subscriptions.push(
        generateFromFileCommand,
        generateFromFolderCommand,
        openSettingsCommand,
        openPlantUMLPreviewCommand
    );
}

async function generateUMLFromFile(uri: vscode.Uri) {
    const config = vscode.workspace.getConfiguration('umlGenerator');
    const includeRelationships = config.get<boolean>('includeRelationships', true);
    const verbose = config.get<boolean>('verbose', false);
    const autoOpenFile = config.get<boolean>('autoOpenFile', true);

    // Fixed: isFolder should be false for single files
    await generateUMLFromPath(uri.fsPath, false, {
        includeRelationships,
        verbose,
        autoOpenFile
    });
}

async function generateUMLFromFolder(uri: vscode.Uri) {
    const config = vscode.workspace.getConfiguration('umlGenerator');
    const includeRelationships = config.get<boolean>('includeRelationships', true);
    const verbose = config.get<boolean>('verbose', false);
    const autoOpenFile = config.get<boolean>('autoOpenFile', true);

    // Correct: isFolder should be true for folders
    await generateUMLFromPath(uri.fsPath, true, {
        includeRelationships,
        verbose,
        autoOpenFile
    });
}

interface UMLGeneratorOptions {
    includeRelationships: boolean;
    verbose: boolean;
    autoOpenFile: boolean;
}

async function generateUMLFromPath(inputPath: string, isFolder: boolean, options: UMLGeneratorOptions) {
    return new Promise<void>((resolve, reject) => {
        vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: "Generating UML Diagram",
                cancellable: false
            }, async (progress) => {
                try {
                    progress.report({ increment: 0, message: "Starting UML generation..." });
                    const jarPath = await getJarPath();
                    if (!jarPath) {
                        throw new Error('UML Generator Jar not found');
                    }
                    
                    let outputDir: string;
                    let outputFile: string;
                    let inputName: string;

                    const config = vscode.workspace.getConfiguration('umlGenerator');
                    const customOutputDir = config.get<string>('outputDirectory');

                    if (isFolder) {
                        if (customOutputDir) {
                            const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
                            outputDir = workspaceRoot ? path.join(workspaceRoot, customOutputDir) : path.join(inputPath, customOutputDir);
                        } else {
                            outputDir = inputPath; // Original behavior
                        }
                        inputName = path.basename(inputPath);
                        outputFile = path.join(outputDir, `${inputName}.puml`);
                    } else {
                        if (customOutputDir) {
                            const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
                            outputDir = workspaceRoot ? path.join(workspaceRoot, customOutputDir) : path.join(path.dirname(inputPath), customOutputDir);
                        } else {
                            outputDir = path.dirname(inputPath); // Original behavior
                        }
                        inputName = path.basename(inputPath, '.java'); 
                        outputFile = path.join(outputDir, `${inputName}.puml`);
                    }
                    
                    if(!FileSystem.existsSync(outputDir)) {
                        FileSystem.mkdirSync(outputDir, {recursive: true});
                    }
                    
                    const args = ['-jar', jarPath, '-i', inputPath, '-o', outputFile];
                    if (!options.includeRelationships) {
                        args.push('--no-relationship');
                    }
                    if (options.verbose) {
                        args.push('-v');
                    }

                    // Debug logging
                    console.log(`Running command: java ${args.join(' ')}`);
                    console.log(`Expected output file: ${outputFile}`);

                    progress.report({increment: 25, message:"Running UML generator..."});

                    const javaProcess = spawn('java', args, {
                        cwd: path.dirname(jarPath)
                    });

                    let output = '';
                    let errorOutput = '';

                    javaProcess.stdout?.on('data', (data) => {
                        output += data.toString();
                        if (options.verbose) {
                            console.log(`stdout: ${data}`);
                        }
                    });

                    javaProcess.stderr?.on('data', (data) => {
                        errorOutput += data.toString();
                        if (options.verbose) {
                            console.error(`stderr: ${data}`);
                        }
                    });

                    javaProcess.on('close', async (code) => {
                        try {
                            progress.report({increment: 75, message: "Processing results..."});
                            
                            console.log(`Java process exited with code: ${code}`);
                            console.log(`stdout: ${output}`);
                            console.log(`stderr: ${errorOutput}`);
                            console.log(`Output file exists: ${FileSystem.existsSync(outputFile)}`);

                            if (code !== 0) {
                                throw new Error(`Java process failed with code ${code}. Error: ${errorOutput || 'No error output'}`);
                            }

                            if (!FileSystem.existsSync(outputFile)) {
                                throw new Error(`Output file was not created: ${outputFile}`);
                            }

                            const fileStats = FileSystem.statSync(outputFile);
                            if (fileStats.size === 0) {
                                throw new Error(`Output file is empty: ${outputFile}`);
                            }

                            const generatedContent = FileSystem.readFileSync(outputFile, 'utf8');
                            if (!generatedContent.trim()) {
                                throw new Error(`Output file contains no content: ${outputFile}`);
                            }

                            if (!generatedContent.includes('@startuml') || !generatedContent.includes('@enduml')) {
                                throw new Error(`Output file does not contain valid PlantUML content: ${outputFile}`);
                            }

                            // Extract metadata for enhanced message
                            const metadata = extractUMLMetadata(generatedContent);
                            const urlMessage = metadata ? ` (URL: ${metadata.url})` : '';

                            // Success!
                            const message = `UML diagram generated successfully: ${outputFile}${urlMessage}`;

                            vscode.window.showInformationMessage(message, 'Open File', 'Open Preview', 'Open Folder').then(selection => {
                                if (selection === "Open File") {
                                    vscode.commands.executeCommand('vscode.open', vscode.Uri.file(outputFile));
                                } else if (selection === "Open Preview") {
                                    vscode.commands.executeCommand('umlGenerator.openWebView', vscode.Uri.file(outputFile));
                                } else if (selection === "Open Folder") {
                                    vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file(outputFile));
                                }
                            });
                            
                            if (options.autoOpenFile) {
                                await vscode.commands.executeCommand('vscode.open', vscode.Uri.file(outputFile));
                            }
                            
                            progress.report({increment: 100, message: "Done!"});
                            resolve();                            
                        } catch (error) {
                            reject(error);
                        }
                    });
                    
                    javaProcess.on('error', (error) => {
                        reject(new Error(`Failed to start java process: ${error.message}`));
                    });

                } catch (error) {
                    reject(error);
                }
            }
        );
    });
}

async function getJarPath(): Promise<string | null> {
    const config = vscode.workspace.getConfiguration('umlGenerator');
    const customJarPath = config.get<string>('jarPath');
    
    // Fixed: Check custom JAR path first
    if (customJarPath && FileSystem.existsSync(customJarPath)) {
        return customJarPath;
    }
    
    // Check bundled JAR
    const extensionPath = vscode.extensions.getExtension('your-publisher-name.uml-generator')?.extensionPath;
    if (extensionPath) {
        const bundledJarPath = path.join(extensionPath, 'resources', 'uml-generator.jar');
        if (FileSystem.existsSync(bundledJarPath)) {
            return bundledJarPath;
        }
    }
    
    // Check common paths
    const commonPaths = [
        './uml-generator.jar',
        '../v2/target/uml-generator.jar',
        './v2/target/uml-generator.jar'
    ];

    for (const jarPath of commonPaths) {
        const resolvedPath = path.resolve(jarPath);
        if (FileSystem.existsSync(resolvedPath)) {
            return resolvedPath;
        }
    }

    // Handle JAR not found
    const result = await vscode.window.showErrorMessage(
        'UML Generator Jar not found. Please configure the JAR path in settings.',
        'Open Settings',
        'Browse for Jar'
    );

    if (result === 'Open Settings') {
        vscode.commands.executeCommand('workbench.action.openSettings', 'umlGenerator.jarPath');
    } else if (result === 'Browse for Jar') {
        const jarUri = await vscode.window.showOpenDialog({
            canSelectFiles: true,
            canSelectFolders: false,
            canSelectMany: false,
            filters: {
                'JAR Files': ['jar']
            }
        });
        if (jarUri && jarUri[0]) {
            await config.update('jarPath', jarUri[0].fsPath, vscode.ConfigurationTarget.Global);
            return jarUri[0].fsPath;
        }
    }
    return null;
}

export function deactivate() {
    console.log('UML Generator extension is now deactivated');
}