@startuml
skinparam classAttributeIconSize 0
hide circle 
interface Animal {
+{abstract}makeSound() : void
+{abstract}eat() : void
+{abstract}eating(String : e) : void
}
@enduml
@startuml
skinparam classAttributeIconSize 0
hide circle 
class Cat {
-name : String
<<create>> +Cat(name: String)
+makeSound() : void
+eat() : void
+eating(e: String) : void
+scratch() : void
}
@enduml
Cat ..|> Animal
@startuml
skinparam classAttributeIconSize 0
hide circle 
class Dog {
-name : String
<<create>> +Dog(name: String)
+makeSound() : void
+eat() : void
+eating(e: String) : void
+fetch() : void
}
@enduml
Dog ..|> Animal

